apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: deploy-config
spec:
  nodePlacement:
    nodeSelector:
      "kubernetes.io/os": "linux"
      "kubernetes.io/arch": "amd64"
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
