apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo
subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: open-cluster-management-agent-addon

