apiVersion: authentication.open-cluster-management.io/v1alpha1
kind: ManagedServiceAccount
metadata:
  name: demo-sa
  namespace: cluster1
spec:
  rotation:
    enabled: true
    validity: "72h0m0s"

